export type NoteSection = "situation" | "intervention" | "response" | "plan";
export type NoteStatus = "draft" | "submitted_for_review" | "changes_requested" | "approved";
export type NoteSource = "human" | "ai_assisted";
export interface WorkspaceContext { tenantId: string; actor: { type: "user" | "agent" | "service"; reference: string; role: "clinician" | "supervisor" | "administrator" | "agent" }; authorizationDecisionReference: string; }
export interface NoteContent { situation: string; intervention: string; response: string; plan: string; }
export interface WorkspaceNote { id: string; tenantId: string; caseId: string; authorReference: string; source: NoteSource; content: NoteContent; status: NoteStatus; version: number; complianceBlockers: string[]; reviewerReference?: string; reviewNote?: string; createdAt: string; updatedAt: string; }
export interface WorkspaceAuditEvent { eventId: string; tenantId: string; noteId: string; actorReference: string; action: "draft_created" | "compliance_checked" | "submitted_for_review" | "changes_requested" | "approved"; occurredAt: string; authorizationDecisionReference: string; details: Record<string, string | number | boolean | string[]>; }
export interface WorkspaceStore { getCase(tenantId: string, caseId: string): Promise<{ id: string; tenantId: string; status: "active" | "closed" } | null>; getNote(tenantId: string, noteId: string): Promise<WorkspaceNote | null>; saveNote(note: WorkspaceNote): Promise<void>; appendAudit(event: WorkspaceAuditEvent): Promise<void>; }
export type WorkspacePolicy = (context: WorkspaceContext, action: string) => Promise<boolean>;
export class WorkspaceError extends Error { constructor(readonly code: string) { super(code); this.name = "WorkspaceError"; } }
function requireHuman(c: WorkspaceContext): void { if (!c.tenantId || !c.actor?.reference || !c.authorizationDecisionReference) throw new WorkspaceError("AUTH_CONTEXT_REQUIRED"); if (c.actor.type !== "user") throw new WorkspaceError("HUMAN_ACTOR_REQUIRED"); }
function validateContent(c: NoteContent): string[] { const b: string[] = []; for (const s of ["situation", "intervention", "response", "plan"] as const) if (typeof c?.[s] !== "string" || c[s].trim().length < 8) b.push("SECTION_INCOMPLETE:" + s.toUpperCase()); return b; }
function safeContent(c: NoteContent): NoteContent { if (!c || typeof c !== "object") throw new WorkspaceError("NOTE_CONTENT_REQUIRED"); for (const s of ["situation", "intervention", "response", "plan"] as const) if (typeof c[s] !== "string" || c[s].length > 5000) throw new WorkspaceError("SECTION_INVALID:" + s.toUpperCase()); return { situation: c.situation.trim(), intervention: c.intervention.trim(), response: c.response.trim(), plan: c.plan.trim() }; }
export class ClientCaseWorkspace {
 constructor(private readonly store: WorkspaceStore, private readonly authorize: WorkspacePolicy, private readonly now: () => Date = () => new Date(), private readonly makeId: () => string = () => crypto.randomUUID()) {}
 private async allowed(c: WorkspaceContext, action: string) { requireHuman(c); if (!(await this.authorize(c, action))) throw new WorkspaceError("POLICY_DENIED"); }
 private async audit(c: WorkspaceContext, n: WorkspaceNote, action: WorkspaceAuditEvent["action"], details: WorkspaceAuditEvent["details"] = {}) { await this.store.appendAudit({ eventId: this.makeId(), tenantId: c.tenantId, noteId: n.id, actorReference: c.actor.reference, action, occurredAt: this.now().toISOString(), authorizationDecisionReference: c.authorizationDecisionReference, details }); }
 async createDraft(c: WorkspaceContext, input: { caseId: string; content: NoteContent; source: NoteSource }): Promise<WorkspaceNote> { await this.allowed(c, "workspace.note.create"); const cr = await this.store.getCase(c.tenantId, input.caseId); if (!cr || cr.tenantId !== c.tenantId) throw new WorkspaceError("CASE_NOT_FOUND"); if (cr.status !== "active") throw new WorkspaceError("CASE_NOT_ACTIVE"); if (input.source !== "human" && input.source !== "ai_assisted") throw new WorkspaceError("NOTE_SOURCE_INVALID"); const content = safeContent(input.content); const time = this.now().toISOString(); const n: WorkspaceNote = { id: this.makeId(), tenantId: c.tenantId, caseId: cr.id, authorReference: c.actor.reference, source: input.source, content, status: "draft", version: 1, complianceBlockers: validateContent(content), createdAt: time, updatedAt: time }; await this.store.saveNote(n); await this.audit(c, n, "draft_created", { source: input.source, version: 1 }); return n; }
 async checkCompliance(c: WorkspaceContext, noteId: string): Promise<WorkspaceNote> { await this.allowed(c, "workspace.note.check"); const n = await this.store.getNote(c.tenantId, noteId); if (!n) throw new WorkspaceError("NOTE_NOT_FOUND"); if (n.status === "approved") throw new WorkspaceError("NOTE_ALREADY_APPROVED"); const u = { ...n, complianceBlockers: validateContent(n.content), updatedAt: this.now().toISOString() }; await this.store.saveNote(u); await this.audit(c, u, "compliance_checked", { blockers: u.complianceBlockers }); return u; }
 async submitForReview(c: WorkspaceContext, noteId: string): Promise<WorkspaceNote> { await this.allowed(c, "workspace.note.submit"); const n = await this.store.getNote(c.tenantId, noteId); if (!n) throw new WorkspaceError("NOTE_NOT_FOUND"); if (n.status !== "draft" && n.status !== "changes_requested") throw new WorkspaceError("NOTE_STATE_INVALID"); const blockers = validateContent(n.content); if (blockers.length) throw new WorkspaceError("COMPLIANCE_BLOCKED:" + blockers.join(",")); const u: WorkspaceNote = { ...n, status: "submitted_for_review", complianceBlockers: [], version: n.version + 1, updatedAt: this.now().toISOString() }; await this.store.saveNote(u); await this.audit(c, u, "submitted_for_review", { version: u.version, source: u.source }); return u; }
 async review(c: WorkspaceContext, input: { noteId: string; decision: "approve" | "request_changes"; note: string }): Promise<WorkspaceNote> { await this.allowed(c, input.decision === "approve" ? "workspace.note.approve" : "workspace.note.request_changes"); if (c.actor.role !== "supervisor" && c.actor.role !== "administrator") throw new WorkspaceError("SUPERVISOR_ROLE_REQUIRED"); if (!input.note?.trim() || input.note.trim().length > 2000) throw new WorkspaceError("REVIEW_NOTE_REQUIRED"); const n = await this.store.getNote(c.tenantId, input.noteId); if (!n) throw new WorkspaceError("NOTE_NOT_FOUND"); if (n.status !== "submitted_for_review") throw new WorkspaceError("NOTE_NOT_AWAITING_REVIEW"); if (n.authorReference === c.actor.reference) throw new WorkspaceError("SELF_APPROVAL_FORBIDDEN"); const status: NoteStatus = input.decision === "approve" ? "approved" : "changes_requested"; const u: WorkspaceNote = { ...n, status, reviewerReference: c.actor.reference, reviewNote: input.note.trim(), version: n.version + 1, updatedAt: this.now().toISOString() }; await this.store.saveNote(u); await this.audit(c, u, input.decision === "approve" ? "approved" : "changes_requested", { version: u.version, reviewNote: u.reviewNote || "" }); return u; }
}