import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { randomUUID } from "node:crypto";
import { Pool } from "pg";
import { DeploymentEvidenceLedger, type EvidenceContext } from "../src/deployment-evidence-ledger";
const suite=process.env.DATABASE_URL?describe:describe.skip;
const context:EvidenceContext={tenantId:randomUUID(),actor:{type:"user",reference:"release-reviewer-57"},authorizationDecisionReference:"authz://synthetic/release-57"};
const report=()=>({schemaVersion:"1.0",reportType:"nova-deployment-smoke",runId:"smoke_run_"+randomUUID().replace(/-/g,"").slice(0,20),startedAt:"2026-10-09T08:00:00.000Z",completedAt:"2026-10-09T08:00:01.000Z",baseUrlConfigured:true,result:"passed",passedChecks:1,totalChecks:1,checks:[{name:"readiness",passed:true,status:200}],limitations:["Synthetic integration fixture; no live deployment."]});
suite("Build 57 PostgreSQL deployment evidence ledger",()=>{
 const pool=new Pool({connectionString:process.env.DATABASE_URL,max:6});
 beforeAll(async()=>{const client=await pool.connect();try{await client.query("SELECT pg_advisory_lock(570057)");for(const path of ["builds/57-nova-deployment-evidence-ledger/sql/build_57_deployment_evidence.sql"])await client.query(await readFile(resolve(process.cwd(),path),"utf8"));await client.query("SELECT pg_advisory_unlock(570057)");}finally{client.release();}});
 afterAll(async()=>{await pool.end();});
 const validInput=()=>({environment:"staging",commitSha:"b".repeat(40),smokeReport:report(),testRunUrl:"https://github.com/novacaristic/novacaris-platform/actions/runs/123456789",reviewerActor:"release-reviewer-57",approvalReference:"approval-"+randomUUID(),requestId:randomUUID()});
 it("records eligible evidence once and returns the existing row for an idempotent replay",async()=>{const input=validInput();const service=new DeploymentEvidenceLedger(pool,async()=>true);const a=await service.record(context,input);const b=await service.record(context,input);expect(a.eligible).toBe(true);expect(a.ledgerId).toBe(b.ledgerId);expect(b.replayed).toBe(true);const count=await pool.query("SELECT count(*)::int n FROM nova_deployment_evidence_audit WHERE ledger_id=$1",[a.ledgerId]);expect(count.rows[0].n).toBe(1);});
 it("records failed evidence but blocks release approval",async()=>{const input=validInput();input.smokeReport={...report(),result:"failed",checks:[{name:"readiness",passed:false,status:503}],passedChecks:0,totalChecks:1};const service=new DeploymentEvidenceLedger(pool,async()=>true);const row=await service.record(context,input);expect(row.eligible).toBe(false);await expect(service.approve(context,row.ledgerId!,"approval-blocked")).rejects.toThrow("DEPLOYMENT_RELEASE_GATE_BLOCKED");});
 it("requires human identity and policy authorization",async()=>{const denied=new DeploymentEvidenceLedger(pool,async()=>false);await expect(denied.record(context,validInput())).rejects.toThrow("DEPLOYMENT_EVIDENCE_RECORD_FORBIDDEN");await expect(new DeploymentEvidenceLedger(pool,async()=>true).record({...context,actor:{type:"agent",reference:"mr-nova"}},validInput())).rejects.toThrow("DEPLOYMENT_EVIDENCE_HUMAN_ACTOR_REQUIRED");});
 it("requires eligible evidence for approval and records an append-only approval event",async()=>{const service=new DeploymentEvidenceLedger(pool,async()=>true);const input=validInput();const row=await service.record(context,input);const approval=input.approvalReference!;expect(await service.approve(context,row.ledgerId!,approval)).toMatchObject({approved:true,replayed:false});expect(await service.approve(context,row.ledgerId!,approval)).toMatchObject({approved:true,replayed:true});const audit=await pool.query("SELECT action FROM nova_deployment_evidence_audit WHERE ledger_id=$1 ORDER BY id",[row.ledgerId]);expect(audit.rows.map(x=>x.action)).toEqual(["release_evidence_recorded","release_approval_recorded"]);await expect(pool.query("UPDATE nova_deployment_evidence_audit SET details='{}'::jsonb WHERE ledger_id=$1",[row.ledgerId])).rejects.toThrow("DEPLOYMENT_EVIDENCE_AUDIT_APPEND_ONLY");});
});
