import { describe, expect, it } from "vitest";
import { evaluateReleaseGate, validateSmokeReport } from "../src/release-gate";
const goodReport = () => ({ schemaVersion:"1.0", reportType:"nova-deployment-smoke", runId:"smoke_run_1234", startedAt:"2026-10-09T08:00:00.000Z", completedAt:"2026-10-09T08:00:01.000Z", baseUrlConfigured:true, result:"passed", passedChecks:2,totalChecks:2,checks:[{name:"liveness",passed:true,status:200},{name:"readiness",passed:true,status:200}],limitations:["HTTP smoke checks only."] });
const goodInput = () => ({environment:"staging",commitSha:"a".repeat(40),smokeReport:goodReport(),testRunUrl:"https://github.com/novacaristic/novacaris-platform/actions/runs/123456789",reviewerActor:"human-reviewer",approvalReference:"release-approval-2026-10"});
describe("Build 57 deployment release gate",()=>{
 it("accepts a well-formed all-green smoke report and explicit human approval metadata",()=>{const r=evaluateReleaseGate(goodInput());expect(r.eligible).toBe(true);expect(r.blockers).toEqual([]);});
 it("blocks failed smoke reports and forged pass counts",()=>{const input=goodInput();input.smokeReport={...goodReport(),result:"passed",checks:[{name:"liveness",passed:true,status:200},{name:"database",passed:false,status:503}],passedChecks:2,totalChecks:2};const r=evaluateReleaseGate(input);expect(r.eligible).toBe(false);expect(r.blockers).toContain("SMOKE_REPORT_COUNTS_MISMATCH");expect(r.blockers).toContain("SMOKE_REPORT_CHECKS_NOT_ALL_PASSED");});
 it("blocks missing reviewer, approval reference, bad commit, and non-HTTPS CI links",()=>{const input=goodInput();input.reviewerActor="";input.approvalReference="";input.commitSha="main";input.testRunUrl="http://example.com";const r=evaluateReleaseGate(input);expect(r.eligible).toBe(false);expect(r.blockers).toContain("RELEASE_COMMIT_SHA_INVALID");expect(r.blockers).toContain("RELEASE_HUMAN_REVIEWER_REQUIRED");expect(r.blockers).toContain("RELEASE_APPROVAL_REFERENCE_REQUIRED");});
 it("rejects invalid report schema, empty checks, and invalid timestamps",()=>{expect(validateSmokeReport({}).blockers.length).toBeGreaterThan(0);const input=goodInput();input.smokeReport={...goodReport(),checks:[],passedChecks:0,totalChecks:0,startedAt:"bad"};expect(evaluateReleaseGate(input).eligible).toBe(false);});
 it("rejects malformed smoke report fields rather than trusting an asserted passed result",()=>{const input=goodInput();input.smokeReport={...goodReport(),baseUrlConfigured:false};const r=evaluateReleaseGate(input);expect(r.blockers).toContain("SMOKE_REPORT_BASE_URL_MISSING");});
});
